import { useEffect, useState } from "react";
import { Plus, Pencil, Trash2, Star } from "lucide-react";
import { toast } from "sonner";
import useTestimonials from "@/hooks/useTestimonials";
import { getProducts } from "@/services/products.service";
import { getCustomers } from "@/services/customers.service";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const blank = { productId: "", customerId: "", title: "", description: "", ranking: "5", experienceType: "General", certificatedPurchase: false };
const Testimonials = () => {
  const { testimonials, loading, error, addTestimonial, editTestimonial, removeTestimonial } = useTestimonials();
  const [products, setProducts] = useState([]), [customers, setCustomers] = useState([]), [open, setOpen] = useState(false), [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([getProducts(), getCustomers()]).then(([p, c]) => { setProducts(p); setCustomers(c); }).catch((err) => toast.error("No se pudieron cargar los datos.", { description: err.message })); }, []);
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const openCreate = () => { setEditing(null); setForm(blank); setOpen(true); };
  const openEdit = (review) => { setEditing(review); setForm({ productId: review.productId?._id || review.productId, customerId: review.customerId?._id || review.customerId, title: review.title, description: review.description, ranking: review.ranking, experienceType: review.experienceType, certificatedPurchase: Boolean(review.certificatedPurchase) }); setOpen(true); };
  const save = async (event) => { event.preventDefault(); try { setSaving(true); if (editing) await editTestimonial(editing._id, form); else await addTestimonial(form); toast.success(editing ? "Testimonio actualizado." : "Testimonio creado."); setOpen(false); } catch (err) { toast.error("No se pudo guardar.", { description: err.message }); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm("¿Eliminar este testimonio?")) return; try { await removeTestimonial(id); toast.success("Testimonio eliminado."); } catch (err) { toast.error("No se pudo eliminar.", { description: err.message }); } };
  return <div className="p-6 space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Testimonios</h1><p className="text-sm text-muted-foreground">Gestiona las reseñas de productos.</p></div><Button onClick={openCreate}><Plus /> Nuevo testimonio</Button></div>
    {error && <p className="text-sm text-red-600">{error}</p>}<Card><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left"><tr><th className="p-4">Producto</th><th className="p-4">Cliente</th><th className="p-4">Testimonio</th><th className="p-4">Puntuación</th><th className="p-4">Acciones</th></tr></thead><tbody>{loading ? <tr><td colSpan="5" className="p-6 text-center">Cargando...</td></tr> : testimonials.length === 0 ? <tr><td colSpan="5" className="p-6 text-center text-muted-foreground">No hay testimonios.</td></tr> : testimonials.map((item) => <tr className="border-b" key={item._id}><td className="p-4">{item.productId?.name || "Producto eliminado"}</td><td className="p-4">{item.customerId ? `${item.customerId.name} ${item.customerId.last_name || ""}` : "Cliente eliminado"}</td><td className="p-4 max-w-xs"><p className="font-medium">{item.title}</p><p className="truncate text-muted-foreground">{item.description}</p></td><td className="p-4"><span className="flex items-center gap-1"><Star className="size-4 fill-yellow-400 text-yellow-400" />{item.ranking}</span></td><td className="p-4 whitespace-nowrap"><Button size="icon" variant="ghost" onClick={() => openEdit(item)}><Pencil className="size-4" /></Button><Button size="icon" variant="ghost" onClick={() => remove(item._id)}><Trash2 className="size-4 text-red-600" /></Button></td></tr>)}</tbody></table></CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "Editar" : "Nuevo"} testimonio</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-3"><select required className="w-full border rounded-md p-2" value={form.productId} onChange={(e) => change("productId", e.target.value)}><option value="">Selecciona un producto</option>{products.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select><select required className="w-full border rounded-md p-2" value={form.customerId} onChange={(e) => change("customerId", e.target.value)}><option value="">Selecciona un cliente</option>{customers.map((item) => <option key={item._id} value={item._id}>{item.name} {item.last_name}</option>)}</select><Input required placeholder="Título" value={form.title} onChange={(e) => change("title", e.target.value)} /><Textarea required placeholder="Descripción" value={form.description} onChange={(e) => change("description", e.target.value)} /><div className="flex gap-3"><select className="border rounded-md p-2" value={form.ranking} onChange={(e) => change("ranking", e.target.value)}>{[5,4,3,2,1].map((n) => <option key={n} value={n}>{n} estrellas</option>)}</select><Input required placeholder="Tipo de experiencia" value={form.experienceType} onChange={(e) => change("experienceType", e.target.value)} /></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.certificatedPurchase} onChange={(e) => change("certificatedPurchase", e.target.checked)} />Compra certificada</label><Button className="w-full" disabled={saving}>{saving ? "Guardando..." : "Guardar"}</Button></form></DialogContent></Dialog>
  </div>;
};
export default Testimonials;
